### ISSUE TITLE
Linting breaks on rules with apostrophes

### ISSUE THREAD

**Issue by AndrewDant** [mrob95/vscode-TalonScript#1]
As shown in the image below, when a rule has an apostrophe the linting for that entire command breaks. 

![image](https://user-images.githubusercontent.com/30133577/149000969-6b730a58-d071-4fa8-87a7-ff624384c5b2.png)

**Comment by mirober** [comment]
Thanks, this should be fixed in the latest version (0.3.8)

**Comment by AndrewDant** [comment]
Can confirm it's now working for me.
