### ISSUE TITLE
talon-list as a separate language

### ISSUE THREAD

**Issue by AndreasArvidsson** [mrob95/vscode-TalonScript#4]
Hi love the extension!
I do have one problem with how `.talon-list` is registered as Talon/Talonscript extension. This means that I can't have different settings in vscode for `.talon` and `.talon-list` files.

This is how I have them registered in my own extension, but it appears that your extension wins out and all my Talon list files become Talon script.
https://github.com/AndreasArvidsson/andreas-vscode/blob/af98d31f911291fa310a4bef95282b0362fb840f/package.json#L41-L60

The problem source:
https://github.com/mrob95/vscode-TalonScript/blob/ef653477f5ecd83ccb89a0da4fdb2eb827c5ba59/package.json#L30

**Comment by mirober** [comment]
https://github.com/mrob95/vscode-TalonScript/pull/5

Could you give the latest version a spin and see if this works now?

**Comment by AndreasArvidsson** [comment]
Work like a charm. Thank you!
